using System.ComponentModel.DataAnnotations;
using BankApi.Domain;

namespace BankApi.Contracts;

public class ClientRequest : IValidatableObject
{
    [Required, StringLength(100)]
    public string LastName { get; set; } = null!;

    [Required, StringLength(100)]
    public string FirstName { get; set; } = null!;

    [StringLength(100)]
    public string? MiddleName { get; set; }

    [Required, EmailAddress, StringLength(254)]
    public string Email { get; set; } = null!;

    [Required]
    public DateOnly? BirthDate { get; set; }

    public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
    {
        var today = DateOnly.FromDateTime(DateTime.UtcNow);
        if (BirthDate is { } date && (date >= today || date.Year < 1900))
            yield return new ValidationResult("BirthDate must be in the past and not earlier than 1900.", [nameof(BirthDate)]);
    }
}

public enum ClientSortBy
{
    LastName,
    Email,
    BirthDate,
    CreatedAt
}

public class ClientFilter : PageQuery
{
    /// <summary>Substring of last, first or middle name.</summary>
    [StringLength(100)]
    public string? Search { get; set; }

    /// <summary>Substring of email.</summary>
    [StringLength(254)]
    public string? Email { get; set; }

    /// <summary>Substring of any of the client's phone numbers.</summary>
    [StringLength(16)]
    public string? Phone { get; set; }

    public DateOnly? BirthDateFrom { get; set; }
    public DateOnly? BirthDateTo { get; set; }

    public ClientSortBy SortBy { get; set; } = ClientSortBy.LastName;
    public bool Desc { get; set; }
}

public class PageQuery
{
    [Range(1, int.MaxValue)]
    public int Page { get; set; } = 1;

    [Range(1, 100)]
    public int PageSize { get; set; } = 20;
}

public class PhoneRequest
{
    [Required, RegularExpression(@"^\+?[0-9]{7,15}$", ErrorMessage = "Number must contain 7-15 digits with an optional leading '+'.")]
    public string Number { get; set; } = null!;

    [Required]
    public PhoneType? Type { get; set; }
}

public class AccountCreateRequest
{
    /// <summary>Generated by the server when omitted.</summary>
    [RegularExpression(@"^[0-9]{16,20}$", ErrorMessage = "Number must contain 16-20 digits.")]
    public string? Number { get; set; }

    [StringLength(100)]
    public string? Name { get; set; }

    [Required]
    public Currency? Currency { get; set; }

    [Money(AllowZero = true)]
    public decimal InitialBalance { get; set; }
}

public class AccountUpdateRequest
{
    [StringLength(100)]
    public string? Name { get; set; }
}

public class AmountRequest
{
    [Money]
    public decimal Amount { get; set; }
}

public class CardCreateRequest
{
    /// <summary>Generated by the server when omitted.</summary>
    [RegularExpression(@"^[0-9]{16}$", ErrorMessage = "Number must contain exactly 16 digits.")]
    public string? Number { get; set; }

    /// <summary>Defaults to the client's first and last name.</summary>
    [StringLength(100)]
    public string? HolderName { get; set; }

    [Required]
    public DateOnly? ExpiryDate { get; set; }

    [Required]
    public CardType? Type { get; set; }
}

public class CardUpdateRequest
{
    [Required, StringLength(100)]
    public string HolderName { get; set; } = null!;

    [Required]
    public DateOnly? ExpiryDate { get; set; }

    [Required]
    public CardType? Type { get; set; }
}

public class TransferRequest : IValidatableObject
{
    [Range(1, int.MaxValue)]
    public int FromAccountId { get; set; }

    [Range(1, int.MaxValue)]
    public int ToAccountId { get; set; }

    /// <summary>Optional card of the source account used to initiate the transfer.</summary>
    [Range(1, int.MaxValue)]
    public int? CardId { get; set; }

    [Money]
    public decimal Amount { get; set; }

    [StringLength(250)]
    public string? Description { get; set; }

    public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
    {
        if (FromAccountId == ToAccountId)
            yield return new ValidationResult("Source and destination accounts must differ.", [nameof(ToAccountId)]);
    }
}

public class TransferQuery : PageQuery
{
    /// <summary>Returns only transfers where the account is a source or a destination.</summary>
    public int? AccountId { get; set; }
}

public class RegisterRequest
{
    [Required, RegularExpression(@"^[A-Za-z0-9_.-]{3,50}$", ErrorMessage = "Username must be 3-50 characters: letters, digits, '_', '.', '-'.")]
    public string Username { get; set; } = null!;

    [Required, StringLength(100, MinimumLength = 8)]
    public string Password { get; set; } = null!;
}

public class LoginRequest
{
    [Required]
    public string Username { get; set; } = null!;

    [Required]
    public string Password { get; set; } = null!;
}
